export const enTranslation = {
  translation: {
    byMatch: "By match",
    byStage: "By stage",
    canFindOrCreate: "You can find or create a group from",
    createdBy: "Created by",
    createGroup: "Create group",
    createNewGroup: "Create new group",
    creatingGroup: "Creating group...",
    eight: "Eight-finals",
    exit: "Exit",
    groups: "Groups",
    groupCreated: "Created group. Redirecting...",
    groupNamePH: "Group name",
    groupManifestPH1: "Set of rules (new members must accept them before joining this group)",
    groupManifestPH2: "Is there a bet? Should the looser be punished?",
    groupSearch: "Look for group",
    groupSearching: "Looking for group...",
    groupSearchSuccess: "Group found",
    hide: "Hide",
    join: "Join",
    joinGroup: "Join a group",
    joinedGroup: "Group joined",
    joiningGroup: "Joining group...",
    leaderBoard: "Leader Board",
    members: "Members",
    nextMatches: "Next Matches",
    noGroups: "You don't belong to any group",
    noPredictions: "No pending predictions",
    noPredictionsYet: "You haven't made predictions yet",
    notComingMatches: "There are no matches soon",
    phases: "Phases",
    predictions: "Predictions",
    quarterfinals: "Quarterfinals",
    quickPredictions: "Quick Predictions",
    register: "Register",
    results: "Results",
    resultExact: "Exact result",
    resultNone: "Wrong result",
    resultWinner: "Winner",
    rules: "Rules",
    predict: "Predict",
    scores: "Scores",
    scoresAutomatically:
      "The scores are automatically calculated based on the group's score system",
    scoringSystem: "Scoring system",
    selectGroup: "Select a group:",
    timeLimit: "Time limits",
    timeLimitInfoStage0: "stage start time",
    timeLimitInfoText: "You can make predictions up to",
    timeLimitInfoMatch0: "match start time",
    timeLimitOptionStage0: "Stage beginning",
    timeLimitOptionStage1: "One hour before stage begins",
    timeLimitOptionStage2: "Twelve hours before stage begins",
    timeLimitOptionStage3: "One day before stage begins",
    timeLimitOptionMatch0: "Match beginning",
    timeLimitOptionMatch1: "One hour before match begins",
    timeLimitOptionMatch2: "Twelve hours before match begins",
    timeLimitOptionMatch3: "One day before match begins",
    timeLimitPresent: "You can predict up to",
    timeLimitTitle: "What time do users have to make their predictions?",
    thirdPosition: "Third position",
    thisSection: "this section",
    yourGroups: "Your groups:"
  },
};
