export const enTranslation = {
  translation: {
    canFindOrCreate: "You can find or create a group from",
    createdBy: "Created by",
    creatingGroup: "Creating group...",
    eight: "Eight-finals",
    exit: "Exit",
    groups: "Groups",
    groupCreated: "Created group. Redirecting...",
    groupNamePH: "Group name",
    groupManifestPH1: "Set of rules (new members must accept them before joining this group)",
    groupManifestPH2: "Is there a bet? Should the looser be punished?",
    leaderBoard: "Leader Board",
    nextMatches: "Next Matches",
    noGroups: "You don't belong to any group",
    noPredictions: "No pending predictions",
    noPredictionsYet: "You haven't made predictions yet",
    notComingMatches: "There are no matches soon",
    phases: "Phases",
    predictions: "Predictions",
    quarterfinals: "Quarterfinals",
    quickPredictions: "Quick Predictions",
    register: "Register",
    results: "Results",
    predict: "Predict",
    scores: "Scores",
    scoresAutomatically:
      "The scores are automatically calculated based on the group's score system",
    selectGroup: "Select a group:",
    thirdPosition: "Third position",
    thisSection: "this section",
    yourGroups: "Your groups:"
  },
};
