export const enTranslation = {
  translation: {
    adminPanelHide: "Hide admin panel",
    adminPanelShow: "Show admin panel",
    adminEditTimeInfo1: "You can edit this info up to 5 days before the cup starts",
    adminEditTimeInfo2: "You cannot edit this info anymore",
    areYouSure: "Are you sure?",
    atLeast6: "At least 6 characters",
    backToLogin: "Back to Login",
    byMatch: "By match",
    byMatchDetail: "Each match will have it's own deadline",
    byStage: "By stage",
    byStageDetail: "Matches of the same stage will share the same deadline",
    cancel: "Cancel",
    canFindOrCreate: "You can find or create a group from",
    clickAvatarToChoose: "Click the avatar to choose another one",
    confirm: "Confirm",
    confirmChanges: "Confirm changes",
    copiedLink: "Copied link!",
    createAccount: "Create Account",
    createdBy: "Created by",
    createGroup: "Create group",
    createNewGroup: "Create new group",
    creatingGroup: "Creating group...",
    deleteGroup: "Delete group",
    editProfile: "Edit Profile",
    eight: "Eight-finals",
    exit: "Exit",
    exitGroup: "Leave group",
    firstTime: "First Time? Register",
    forgotPass: "Forgot password",
    goBack: "Go Back",
    groupCreated: "Created group. Redirecting...",
    groupDeleteing: "Removing group",
    groupDeleted: "Group deleted",
    groupDeleteConfirmMsg1: "Are you sure you want to delete this group?",
    groupDeleteConfirmMsg2: "This action cannot be undone",
    grupEditing: "Editing group info...",
    groupEdited: "Group info edited",
    groupManifestPH1:
      "Set of rules (new members must accept them before joining this group)",
    groupManifestPH2: "Is there a bet? Should the looser be punished?",
    groupNamePH: "Group name",
    groupNameRequirements: "Group name must be less than 20 characters.",
    groupPhase: "Group Phase",
    groups: "Groups",
    groupCheckConfirm: "To confirm please enter group's name",
    groupLeaving: "Leaving group...",
    groupLeaveConfirmMsg1: "Are you sure you want to leave?",
    groupLeaveConfirmMsg2: "Your progress will be lost",
    groupLeft: "You left the group",
    groupSearch: "Look for group",
    groupSearching: "Looking for group...",
    groupSearchSuccess: "Group found",
    hide: "Hide",
    insertEmail: "Enter email",
    insertImageLink: "Enter a link to an image",
    insertPass: "Enter password",
    insertUsername: "Enter username",
    insertUserName: "Enter username",
    insertValidEmail: "Enter valid email",
    inviteToGroup: "Invite other players!",
    inviteTitle: "Join my Chumbazo group",
    inviteBody: "You can join by clicking the following link: ",
    join: "Join",
    joinedGroup: "Group joined",
    joinGroup: "Join a group",
    joiningGroup: "Joining group...",
    leaderBoard: "Leader Board",
    loginIn: "Login in...",
    loginSuccess: "Login successful",
    loginError: "Error while logging in with Google",
    loginValidation: "Validating account...",
    members: "Members",
    nextMatches: "Next Matches",
    noGroups: "You don't belong to any group",
    noPredictions: "No pending predictions",
    noPredictionsYet: "You haven't made predictions yet",
    notComingMatches: "There are no matches soon",
    orChooseFromList: "choose from list",
    passRequirements: "Password must have at least 6 characters",
    phases: "Phases",
    predict: "Predict",
    predictions: "Predictions",
    profileUpdated: "Profile updated",
    quarterfinals: "Quarterfinals",
    quickPredictions: "Quick Predictions",
    register: "Register",
    resultExact: "Exact result",
    resultNone: "Wrong result",
    results: "Results",
    resultWinner: "Winner",
    rules: "Rules",
    scores: "Scores",
    scoresAutomatically:
      "The scores are automatically calculated based on the group's score system",
    scoringSystem: "Scoring system",
    select: "Select",
    selectGroup: "Select a group:",
    sendingChanges: "Sending changes...",
    slogan: "Predict Qatar 2022 results",
    thirdPosition: "Third position",
    thisSection: "this section",
    timeLimit: "Time limits",
    timeLimitInfoMatch0: "match start time",
    timeLimitInfoStage0: "stage start time",
    timeLimitInfoText: "You can make predictions up to",
    timeLimitOptionMatch0: "Match beginning",
    timeLimitOptionMatch1: "One hour before match begins",
    timeLimitOptionMatch2: "Twelve hours before match begins",
    timeLimitOptionMatch3: "One day before match begins",
    timeLimitOptionStage0: "Stage beginning",
    timeLimitOptionStage1: "One hour before stage begins",
    timeLimitOptionStage2: "Twelve hours before stage begins",
    timeLimitOptionStage3: "One day before stage begins",
    timeLimitPresent: "You can predict up to",
    timeLimitTitle: "What time do users have to make their predictions?",
    username: "Username",
    usernameRequirementsMatches: "Username must be alpha numeric",
    usernameRequirementsMax: "Username must be less than 20 characters",
    withGoogle: "with Google",
    yourGroups: "Your groups:",
    yourNewProfile: "Your new profile",
    landing: {
      main: "Join, predict and win",
      first: {
        title: "Create a group and send invitations",
        subtitle:
          "You can customize the score system and the prediction limit date",
      },
      second: {
        title: "Join existing groups",
        subtitle: "You can get the invite through WhatsApp, email or Telegram",
      },
      third: {
        title: "Check the included fixture",
        subtitle: "It's updated with the latest data from the FIFA.",
      },
    },
  },
};
