export const esTranslation = {
  translation: {
    canFindOrCreate: "Puedes encontrar o crear uno desde",
    createdBy: "Creado por",
    creatingGroup: "Creando grupo...",
    editProfile: "Editar perfil",
    eight: "Octavos",
    exit: "Salir",
    groupCreated: "Grupo creado con éxito. Redirigiendo...",
    groupManifestPH1:
      "Reglamento (los miembros deberán aceptar estos términos al ingresar)",
    groupManifestPH2: "¿Qué se apuesta? ¿Hay prenda para el último?",
    groupNamePH: "Nombre del grupo",
    groupPhase: "Fase de grupos",
    groups: "Grupos",
    leaderBoard: "Ranking de usuarios",
    nextMatches: "Próximos partidos",
    noGroups: "No perteneces a ningún grupo",
    noPredictions: "No hay predicciones pendientes",
    noPredictionsYet: "Aún no hiciste predicciones",
    notComingMatches: "No se aproximan partidos",
    phases: "Fases",
    predict: "Predecir",
    predictions: "Predicciones",
    quarterfinals: "Cuartos",
    quickPredictions: "Predicciones al paso",
    register: "Registrarse",
    results: "Resultados",
    scores: "Puntajes",
    scoresAutomatically:
      "Los puntajes se calculan automáticamente según el sistema de puntajes de cada grupo",
    selectGroup: "Seleccioná un grupo:",
    thirdPosition: "Tercer puesto",
    thisSection: "esta sección",
    yourGroups: "Grupos en los que estás participando:",
  },
};
