export const esTranslation = {
  translation: {
    canFindOrCreate: "Puedes encontrar o crear uno desde",
    createdBy: "Creado por",
    eight: "Octavos",
    exit: "Salir",
    groups: "Grupos",
    leaderBoard: "Ranking de usuarios",
    nextMatches: "Próximos partidos",
    noGroups: "No perteneces a ningún grupo",
    noPredictions: "No hay predicciones pendientes",
    noPredictionsYet: "Aún no hiciste predicciones",
    notComingMatches: "No se aproximan partidos",
    phases: "Fases",
    predictions: "Predicciones",
    quarterfinals: "Cuartos",
    quickPredictions: "Predicciones al paso",
    register: "Registrarse",
    scores: "Puntajes",
    selectGroup: "Seleccioná un grupo:",
    thirdPosition: "Tercer puesto",
    thisSection: "esta sección",
  },
};
